### PR TITLE
Use consistent style indentation and insert final newlines consistently

### PR DESCRIPTION
**Pull request by treyhunner**
I don't know if you feel this is worthwhile, but I wasn't sure about 2 vs 4 spaces when contributing #2 so I made this to add a `.editorconfig` file and convert to 4 spaces and final newlines present everywhere.

### CODE REVIEW

**Comment by sethmlarson** [comment]
I like the formatting changes, but I'm not usually a fan of checking in editor configuration files. Can we use some automated formatting tools for these languages instead via nox?

**Comment by treyhunner** [comment]
Preface: I have *too many* thoughts about this issue. Please feel free to go with your own instinct here instead. But I might want to pick your brain at the next in-person conference to better understand your thinking here. 😊

> Can we use some automated formatting tools for these languages instead via nox?

Unfortunately, probably not. I haven't checked in the last couple years, but it's unlikely that a good one exists for HTML files that have embedded JS and CSS. Please feel free to prove me wrong if you find one that works though!

Before you read on, note that I helped make EditorConfig about a decade ago, so I'm in no way unbiased here. I [did that thing](https://treyhunner.com/2012/02/editorconfig/) from [that xkcd](https://xkcd.com/927/). That being said, I've thought about this problem quite a bit so I'll try to express my reasoning for this file succinctly.

> I like the formatting changes, but I'm not usually a fan of checking in editor configuration files.

I sympathize with this aversion. I always remove `.vscode` directories and `# vim: ` modeline comments for the same reason. My editor settings don't belong in your code repository.

However, even though this file is called `.editorconfig`, I see this as more akin to the `[tool.black]` or `[tool.autopep8]` section in a `pyproject.toml` file.

Here's my reasoning:

1. EditorConfig settings are all intended to be generic settings about the file format which, if disobeyed, would leave the project maintainers unhappy (4 space indentation for example, but not which color scheme to use).
2. EditorConfig is enforced by the code editor itself rather than auto-formatters because not all communities have a solid auto-formatter that's aware of the [indentation vs alignment](https://stackoverflow.com/a/11536257) problem.
3. The extra file is unfortunate but ultimately useful for universality. Text editors that support EditorConfig out of the box (like PyCharm) and extensions that support EditorConfig (like the VS Code one) need a file to look in and `.editorconfig` is that file. A new file was used instead of piggy-backing on an existing one because there isn't *one* existing file that all programming communities already rely on. Many EditorConfig users might suggest `package.json`, but you and I would probably prefer `pyproject.toml` (though it probably would have been `setup.cfg` when EditorConfig was conceived).
4. Unlike in the Python world, the front end world not only doesn't agree on indentation (every project I have seems to have a different indentation in the `.html` and other front end files), but writing good auto-formatters is more of a challenge than making Black because there's TypeScript, Sass, SCSS, CoffeeScript, JSX, CSS, JS, HTML, HAML, and whatever new language was invented last week which needs its own indentation-vs-alignment aware parser. Delegating to the text editor is the simpler approach in many cases.

**Comment by sethmlarson** [comment]
If there's no other option I'm fine with using `.editorconfig`. Is there a tool for enforcing it programmatically?

**Comment by treyhunner** [comment]
> Is there a tool for enforcing it programmatically?

Yes and no. I found [a GitHub action to validate EditorConfig files](https://github.com/editorconfig-checker/editorconfig-checker) a while back, but it made assumptions about indentation that didn't universally make sense (it mistook alignment for indentation in many files). I [started on my own just for `.py` file validation](https://github.com/treyhunner/editorconfig-python-validator) a few months back but didn't end up following through on that.

If you use the EditorConfig checker I'd recommend disabling indentation validation if you run into issues (possible there won't be any if alignment is avoided).

**Pull request merged**
